<h1 align="center"> Projet BI:  AdventureWorks Cycle Data Analytics</h1>

In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv("Data/AdventureWorksData.csv", delimiter = ";", encoding='utf-8')
print(data.shape)
data.head()

(121253, 45)

,SalesOrderLineKey,ResellerKey,CustomerKey,ProductKey,OrderDateKey,DueDateKey,ShipDateKey,SalesTerritoryKey,Order Quantity,Unit Price,...,Region,Country,Group,DateKey,Date,Fiscal Year,Fiscal Quarter,Month,Full Date,MonthKey
0,43659001,676,-1,349,20170702,20170712,20170709.0,5,1,2024.994,...,Southeast,United States,North America,20170712,2017-07-12,FY2018,FY2018 Q1,2017 Jul,"2017 Jul, 12",201707
1,43659002,676,-1,350,20170702,20170712,20170709.0,5,3,2024.994,...,Southeast,United States,North America,20170712,2017-07-12,FY2018,FY2018 Q1,2017 Jul,"2017 Jul, 12",201707
2,43659003,676,-1,351,20170702,20170712,20170709.0,5,1,2024.994,...,Southeast,United States,North America,20170712,2017-07-12,FY2018,FY2018 Q1,2017 Jul,"2017 Jul, 12",201707
3,43659004,676,-1,344,20170702,20170712,20170709.0,5,1,2039.994,...,Southeast,United States,North America,20170712,2017-07-12,FY2018,FY2018 Q1,2017 Jul,"2017 Jul, 12",201707
4,43659005,676,-1,345,20170702,20170712,20170709.0,5,1,2039.994,...,Southeast,United States,North America,20170712,2017-07-12,FY2018,FY2018 Q1,2017 Jul,"2017 Jul, 12",201707

In [2]:
data.columns

Index(['SalesOrderLineKey', 'ResellerKey', 'CustomerKey', 'ProductKey',
       'OrderDateKey', 'DueDateKey', 'ShipDateKey', 'SalesTerritoryKey',
       'Order Quantity', 'Unit Price', 'Extended Amount',
       'Unit Price Discount Pct', 'Product Standard Cost',
       'Total Product Cost', 'Sales Amount', 'Customer ID', 'Customer', 'City',
       'State-Province', 'Country-Region', 'Postal Code', 'SKU', 'Product',
       'Standard Cost', 'Color', 'List Price', 'Model', 'Subcategory',
       'Category', 'Reseller ID', 'Business Type', 'Reseller', 'Channel',
       'Sales Order', 'Sales Order Line', 'Region', 'Country', 'Group',
       'DateKey', 'Date', 'Fiscal Year', 'Fiscal Quarter', 'Month',
       'Full Date', 'MonthKey'],
      dtype='object')

In [3]:
data.drop(columns = ['Fiscal Year', 'Fiscal Quarter', 'Month', 'Full Date', 'MonthKey','OrderDateKey', 
                     'DueDateKey','ShipDateKey','Extended Amount','Sales Order', 'Sales Order Line',
                     'Unit Price Discount Pct', 'Unit Price', 'Customer ID', 'Postal Code', 'SKU',
                     'Total Product Cost', 'Sales Amount','Standard Cost', 
                     'Reseller ID','State-Province', 'Country-Region','ResellerKey','Reseller'],
          inplace = True)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121253 entries, 0 to 121252
Data columns (total 21 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   SalesOrderLineKey      121253 non-null  int64
 1   CustomerKey            121253 non-null  int64
 2   ProductKey             121253 non-null  int64
 3   SalesTerritoryKey      121253 non-null  int64
 4   Order Quantity         121253 non-null  int64
 5   Product Standard Cost  121253 non-null  float64
 6   Customer               121253 non-null  object
 7   City                   121253 non-null  object
 8   Product                121253 non-null  object
 9   Color                  87109 non-null   object
 10  List Price             121253 non-null  float64
 11  Model                  121253 non-null  object
 12  Subcategory            121253 non-null  object
 13  Category               121253 non-null  object
 14  Business Type          121253 non-null  object
 15  Channel                121253 non-null  object
 16  Region                 121253 non-null  object
 17  Country                121253 non-null  object
 18  Group                  121253 non-null  object
 19  DateKey                121253 non-null  int64
 20  Date                   121253 non-null  object
dtypes: float64(2), int64(6), object(13)
memory usage: 19.4+ MB

 <H1 align="center">Remplacer les valeurs manquantes des clients dans les donnees</H1>

## Afficher les infos manquantes

In [5]:
print(data.loc[data["CustomerKey"] == -1].shape)
data.loc[data["CustomerKey"] == -1, ["CustomerKey","Customer","City", "Country", "Region"]].head()

(60855, 21)

   CustomerKey          Customer              City        Country     Region
0           -1  [Not Applicable]  [Not Applicable]  United States  Southeast
1           -1  [Not Applicable]  [Not Applicable]  United States  Southeast
2           -1  [Not Applicable]  [Not Applicable]  United States  Southeast
3           -1  [Not Applicable]  [Not Applicable]  United States  Southeast
4           -1  [Not Applicable]  [Not Applicable]  United States  Southeast

### Remplacer les infos clients par rapport au pays

In [6]:
def replace_values_for_countries(country_name):
    print("Le nom du pays en cours: " + country_name)
    customer_name = data.loc[data["Country"] == country_name, "Customer"].value_counts().index.tolist()[1]
    print("Le nom du client actif: " + customer_name) 
        # update null values
    customer = data.loc[data["Customer"] == customer_name, ["CustomerKey","Customer","City"]].head(1)
    data.loc[(data["Country"] == country_name) & (data["CustomerKey"] == -1) ,"Customer"] = customer['Customer'].iloc[0]
    data.loc[(data["Country"] == country_name) & (data["CustomerKey"] == -1) ,"City"] = customer['City'].iloc[0]
    data.loc[(data["Country"] == country_name) & (data["CustomerKey"] == -1) ,"CustomerKey"] = customer['CustomerKey'].iloc[0]

In [7]:
countries = data.loc[data["CustomerKey"] == -1, "Country"].value_counts().index.tolist()
for country in countries:
    replace_values_for_countries(country)

Le nom du pays en cours: United States
Le nom du client actif: Jordan Hernandez
Le nom du pays en cours: Canada
Le nom du client actif: Ashley Henderson
Le nom du pays en cours: France
Le nom du client actif: April Shan
Le nom du pays en cours: United Kingdom
Le nom du client actif: Anne Hernandez
Le nom du pays en cours: Germany
Le nom du client actif: Franklin Xu
Le nom du pays en cours: Australia
Le nom du client actif: Jaclyn Xu

In [8]:
print(data.loc[data["CustomerKey"] == -1].shape)
data.loc[data["CustomerKey"] == -1, ["CustomerKey","Customer","City", "Country", "Region"]].head()

(0, 21)

Empty DataFrame
Columns: [CustomerKey, Customer, City, Country, Region]
Index: []

# Importer fichier client

In [9]:
client_2020 = pd.read_excel("Data/Adventure Works Excel.xlsx", sheet_name = "Customers",
                         usecols = ['CustomerKey','Name','BirthDate', 'MaritalStatus',
                                    'Gender', 'YearlyIncome', 'NumberChildrenAtHome', 'Occupation',
                                    'HouseOwnerFlag', 'NumberCarsOwned'])
client_2020.rename(columns = {"Name" : "Customer"}, inplace = True)
print(client_2020.shape) 
client_2020.columns

(18484, 10)

Index(['CustomerKey', 'Customer', 'BirthDate', 'MaritalStatus', 'Gender',
       'YearlyIncome', 'NumberChildrenAtHome', 'Occupation', 'HouseOwnerFlag',
       'NumberCarsOwned'],
      dtype='object')

In [10]:
data = pd.merge(data, client_2020, how="left", on = ["CustomerKey", "Customer"])
print(data.shape)
data.columns

(121253, 29)

Index(['SalesOrderLineKey', 'CustomerKey', 'ProductKey', 'SalesTerritoryKey',
       'Order Quantity', 'Product Standard Cost', 'Customer', 'City',
       'Product', 'Color', 'List Price', 'Model', 'Subcategory', 'Category',
       'Business Type', 'Channel', 'Region', 'Country', 'Group', 'DateKey',
       'Date', 'BirthDate', 'MaritalStatus', 'Gender', 'YearlyIncome',
       'NumberChildrenAtHome', 'Occupation', 'HouseOwnerFlag',
       'NumberCarsOwned'],
      dtype='object')

### Afficher les dates unique de la table

In [11]:
# Ajouter une colonne Annee dans le fichier qui contient seulement l'annee
print("Date : ")
data["Date"].unique()

Date :

array(['2017-07-12', '2018-01-29', '2018-04-11', ..., '2017-12-28',
       '2017-07-21', '2017-10-19'], dtype=object)

In [12]:
data['Date'] = pd.to_datetime(data['Date'], format = '%Y-%m-%d')

In [13]:
data["Date"].unique()

array(['2017-07-12T00:00:00.000000000', '2018-01-29T00:00:00.000000000',
       '2018-04-11T00:00:00.000000000', ...,
       '2017-12-28T00:00:00.000000000', '2017-07-21T00:00:00.000000000',
       '2017-10-19T00:00:00.000000000'], dtype='datetime64[ns]')

### Creation de la colonne Annee

In [14]:
data['Year'] = data['Date'].dt.strftime('%Y')
print("Created Year:")
data["Year"].unique()

Created Year:

array(['2017', '2018', '2019', '2020'], dtype=object)

### Creation de la colonne Mois

In [15]:
data['Month'] = data['Date'].dt.strftime('%m')
print("Created Month :")
data["Month"].unique()

Created Month :

array(['07', '01', '04', '10', '08', '05', '02', '11', '09', '06', '12',
       '03'], dtype=object)

### Creation de la colonne Semaine

In [16]:
data['Week'] = data['Date'].dt.strftime('%W')
print("Created Week:")
data["Week"].unique()

Created Week:

array(['28', '05', '15', '40', '43', '01', '14', '27', '30', '04', '17',
       '03', '29', '41', '32', '19', '06', '45', '34', '46', '07', '21',
       '35', '47', '08', '23', '36', '48', '09', '22', '39', '49', '10',
       '12', '13', '25', '42', '20', '33', '38', '26', '52', '00', '18',
       '50', '16', '24', '31', '51', '37', '02', '11', '44', '53'],
      dtype=object)

### Cration de la colonne Saison

In [17]:
conditions = [
                data["Month"].isin(["11","12","01"]),
                data["Month"].isin(["02","03","04"]),
                data["Month"].isin(["05","06","07"]),
                data["Month"].isin(["08","09","10"])
             ]
saisons = [
                "Winter",
                "Spring",
                "Summer",
                "Autumn"
             ]
data["Season"] = np.select(conditions, saisons)
data["Season"].unique()

array(['Summer', 'Winter', 'Spring', 'Autumn'], dtype=object)

# <H1 align="center">Remplacer les valeurs manquantes dans les donnees</H1><br>

### Afficher le nombre des valeurs nulles dans chaque colonne

In [18]:
data.isnull().sum()

SalesOrderLineKey            0
CustomerKey                  0
ProductKey                   0
SalesTerritoryKey            0
Order Quantity               0
Product Standard Cost        0
Customer                     0
City                         0
Product                      0
Color                    34144
List Price                   0
Model                        0
Subcategory                  0
Category                     0
Business Type                0
Channel                      0
Region                       0
Country                      0
Group                        0
DateKey                      0
Date                         0
BirthDate                    0
MaritalStatus                0
Gender                       0
YearlyIncome                 0
NumberChildrenAtHome         0
Occupation                   0
HouseOwnerFlag               0
NumberCarsOwned              0
Year                         0
Month                        0
Week                         0
Season                       0
dtype: int64

### Remplir les lignes nulles de la colonne Couleur par la couleur la plus fréquente

#### Afficher les couleurs distinctes

In [19]:
data.loc[(~data["Product"].isin(["Red","Yellow","White","Black","Blue", "Silver"]) , "Color")] = "Unknown"
data.loc[data["Product"].str.contains("Red") , "Color"] = "Red"
data.loc[data["Product"].str.contains("Silver") , "Color"] = "Silver"
data.loc[data["Product"].str.contains("Black") , "Color"] = "Black"
data.loc[data["Product"].str.contains("White") , "Color"] = "White"
data.loc[data["Product"].str.contains("Yellow") , "Color"] = "Yellow"
data.loc[data["Product"].str.contains("Blue") , "Color"] = "Blue"
data['Color'].unique()

array(['Black', 'Silver', 'Unknown', 'Blue', 'Red', 'Yellow'],
      dtype=object)

### Afficher le nombre des valeurs nulles dans les donnees apres les modifications

In [20]:
data.isnull().sum()

SalesOrderLineKey        0
CustomerKey              0
ProductKey               0
SalesTerritoryKey        0
Order Quantity           0
Product Standard Cost    0
Customer                 0
City                     0
Product                  0
Color                    0
List Price               0
Model                    0
Subcategory              0
Category                 0
Business Type            0
Channel                  0
Region                   0
Country                  0
Group                    0
DateKey                  0
Date                     0
BirthDate                0
MaritalStatus            0
Gender                   0
YearlyIncome             0
NumberChildrenAtHome     0
Occupation               0
HouseOwnerFlag           0
NumberCarsOwned          0
Year                     0
Month                    0
Week                     0
Season                   0
dtype: int64

In [21]:
data.head()

,SalesOrderLineKey,CustomerKey,ProductKey,SalesTerritoryKey,Order Quantity,Product Standard Cost,Customer,City,Product,Color,...,Gender,YearlyIncome,NumberChildrenAtHome,Occupation,HouseOwnerFlag,NumberCarsOwned,Year,Month,Week,Season
0,43659001,13314,349,5,1,1898.0944,Jordan Hernandez,Grossmont,"Mountain-100 Black, 42",Black,...,M,120000,3,Professional,1,4,2017,07,28,Summer
1,43659002,13314,350,5,3,1898.0944,Jordan Hernandez,Grossmont,"Mountain-100 Black, 44",Black,...,M,120000,3,Professional,1,4,2017,07,28,Summer
2,43659003,13314,351,5,1,1898.0944,Jordan Hernandez,Grossmont,"Mountain-100 Black, 48",Black,...,M,120000,3,Professional,1,4,2017,07,28,Summer
3,43659004,13314,344,5,1,1912.1544,Jordan Hernandez,Grossmont,"Mountain-100 Silver, 38",Silver,...,M,120000,3,Professional,1,4,2017,07,28,Summer
4,43659005,13314,345,5,1,1912.1544,Jordan Hernandez,Grossmont,"Mountain-100 Silver, 42",Silver,...,M,120000,3,Professional,1,4,2017,07,28,Summer

### Calculer la colonne d'age des clients

In [22]:
data["BirthDate"].unique()

array(['1980-08-03T00:00:00.000000000', '1977-05-27T00:00:00.000000000',
       '1984-01-27T00:00:00.000000000', ...,
       '1977-07-07T00:00:00.000000000', '1982-10-21T00:00:00.000000000',
       '1974-03-16T00:00:00.000000000'], dtype='datetime64[ns]')

In [23]:
data["BirthDate"] = data["BirthDate"].dt.strftime('%Y-%m-%d')
data["BirthDate"].unique()

array(['1980-08-03', '1977-05-27', '1984-01-27', ..., '1977-07-07',
       '1982-10-21', '1974-03-16'], dtype=object)

In [24]:
data["BirthDate"].replace('NaT', data["BirthDate"].value_counts().idxmax(), inplace =True)

In [25]:
from datetime import date, datetime
def calculer_age(naissance):
    naissance = datetime.strptime(naissance, '%Y-%m-%d').date()
    today = date.today()
    return today.year - naissance.year - ((today.month, 
                                      today.day) < (naissance.month, 
                                                    naissance.day))
data["Age"] = data["BirthDate"].apply(calculer_age)
data["Age"].unique()

array([42, 45, 39, 37, 26, 48, 61, 28, 29, 27, 30, 33, 58, 38, 24, 46, 41,
       49, 25, 43, 59, 31, 22, 51, 32, 47, 23, 40, 34, 53, 35, 36, 44, 65,
       66, 62, 55, 54, 50, 52, 57, 60, 71, 63, 56, 68, 64, 69, 74, 67, 70,
       72, 82, 73, 75, 81, 83, 78, 77, 84, 76, 86, 90, 91, 89, 80, 85, 79,
       92, 87], dtype=int64)

In [26]:
data["Age Range"] = ['20-40' if ((x >= 20) & (x <= 40)) else '40-60' if ((x > 40) & (x <= 60)) else '60-80' if ((x > 60) & (x <= 80)) else '80+' for x in data['Age']]
data["Age Range"].unique()

array(['40-60', '20-40', '60-80', '80+'], dtype=object)

In [27]:
data.columns

Index(['SalesOrderLineKey', 'CustomerKey', 'ProductKey', 'SalesTerritoryKey',
       'Order Quantity', 'Product Standard Cost', 'Customer', 'City',
       'Product', 'Color', 'List Price', 'Model', 'Subcategory', 'Category',
       'Business Type', 'Channel', 'Region', 'Country', 'Group', 'DateKey',
       'Date', 'BirthDate', 'MaritalStatus', 'Gender', 'YearlyIncome',
       'NumberChildrenAtHome', 'Occupation', 'HouseOwnerFlag',
       'NumberCarsOwned', 'Year', 'Month', 'Week', 'Season', 'Age',
       'Age Range'],
      dtype='object')

In [28]:
data.drop(columns = ['BirthDate','SalesOrderLineKey', 'CustomerKey', 'ProductKey', 'SalesTerritoryKey','DateKey'], inplace = True)

In [29]:
data["HouseOwnerFlag"].unique()

array([1, 0], dtype=int64)

In [30]:
data["HouseOwnerFlag"].replace(to_replace = [1,0],
                                    value= ['YES','NO'], 
                                    inplace = True)
data["HouseOwnerFlag"].unique()

array(['YES', 'NO'], dtype=object)

In [31]:
data["MaritalStatus"].unique()

array(['M', 'S'], dtype=object)

In [32]:
data["MaritalStatus"].replace(to_replace = ["M","S"],
                           value= ['Married','Single'], 
                           inplace = True)
data["MaritalStatus"].unique()

array(['Married', 'Single'], dtype=object)

In [33]:
data["Gender"].unique()

array(['M', 'F'], dtype=object)

In [34]:
data["Gender"].replace(to_replace = ['M', 'F'],
                      value= ['Male','Female'], 
                      inplace = True)
data["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [35]:
data.columns

Index(['Order Quantity', 'Product Standard Cost', 'Customer', 'City',
       'Product', 'Color', 'List Price', 'Model', 'Subcategory', 'Category',
       'Business Type', 'Channel', 'Region', 'Country', 'Group', 'Date',
       'MaritalStatus', 'Gender', 'YearlyIncome', 'NumberChildrenAtHome',
       'Occupation', 'HouseOwnerFlag', 'NumberCarsOwned', 'Year', 'Month',
       'Week', 'Season', 'Age', 'Age Range'],
      dtype='object')

 <H1 align= "center"> Decoupage des fichiers par annees </H1>

In [36]:
data["Year"].unique()

array(['2017', '2018', '2019', '2020'], dtype=object)

In [37]:
data_2017 = data.loc[data["Year"] == '2017']
print(data_2017.shape)

(5278, 29)

In [38]:
data_2017.to_csv("Data/Adventure_works2017.csv", sep=";", encoding="utf-8-sig")

In [39]:
data_2018 = data.loc[data["Year"] == '2018']
print(data_2018.shape)

(18858, 29)

In [40]:
from sqlalchemy import create_engine
import pymysql

In [41]:
engine = create_engine('postgresql://postgres:hkhouya10@localhost:5432/adventurework')
data_2018.to_sql('adventurework', engine,if_exists='replace')

858

In [42]:
data_2019 = data.loc[data["Year"] == '2019']
print(data_2019.shape)

(53849, 29)

In [43]:
engine = create_engine('mysql+pymysql://root:@localhost/adventurework')
cnx = engine.connect()
data_2019.to_sql("adventurework", cnx, if_exists='replace')
cnx.close()

In [44]:
data_2020 = data.loc[data["Year"] == '2020']
print(data_2020.shape)

(43268, 29)

In [45]:
data_2020.to_excel("Data/Adventure_works2020.xlsx", sheet_name = "Adventureworks", encoding="utf-8-sig")